#!/bin/bash
#
# System will be Flatpak-centric #
#
# Fully upgrades system and sets stage for further modifications:
apt update
apt full-upgrade -y
#
# Firmware:
apt install -y firmware-linux firmware-iwlwifi firmware-misc-nonfree mesa-vulkan-drivers
#apt install -y nvidia-driver nvidia-kernel-dkms
#apt install -y firmware-amd-graphics
#
# Backend:
apt install -y flatpak tuned wget p7zip-rar chrome-gnome-shell gamemode
#
# Theming:
apt install -y plymouth-themes adwaita-icon-theme gnome-backgrounds
#apt install -y elementary-xfce-icon-theme
#
# Gaming Toolset:
#apt install -y steam-devices xboxdrv xserver-xorg-input-joystick
#
# GNOME Extensions:
apt install -y gnome-shell-extensions gnome-shell-extension-{dashtodock,caffeine,appindicator,desktop-icons}
#
# GenOS Settings:
apt install -y firefox gnome-software gnome-software-plugin-flatpak
#
# Core GNOME Apps:
#apt install -y gedit geary gnome-calendar gnome-clocks bijiben gnome-sound-recorder
#
# GNOME Multimedia:
apt install -y gnome-music gnome-photos totem cheese
#
# GNOME System Apps:
#apt install -y gnome-control-center gnome-logs gnome-font-viewer deja-dup gnome-extensions-app
#
# GNOME Utils:
#apt install -y gnome-calculator gnome-screenshot gnome-characters gnome-logs evince file-roller
#
# GNOME User Apps:
apt install -y gnome-usage gnome-terminal
#
# GNOME Dev Apps:
#apt install -y gnome-system-monitor gnome-todo gnome-builder devhelp sysprof baobab seahorse tilix tilix-nautilus seahorse-nautilus
#
# GNOME Games:
#apt install -y gnome-chess gnome-2048 gnome-mahjongg gnome-mines
#
# Safe point to clean dependencies:
apt autoremove --purge -y
#
