#!/bin/bash
#
# Enables System Configuration Overrides:
cp ./modules/syst-settings/* /usr/share/glib-2.0/schemas/
#
glib-compile-schemas --strict /usr/share/glib-2.0/schemas/
#
# Tuned profile set as 'Balanced':
systemctl enable --now tuned
tuned-adm profile desktop
#
### Increases Point of Battery Warning
sed -i.bak -e 's/^PercentageLow.*/PercentageLow=15/' -e 's/^PercentageCritical.*/PercentageCritical=5/' -e 's/^PercentageAction.*/PercentageAction=3/' -e 's/^CriticalPowerAction.*/CriticalPowerAction=Hibernate/' /etc/UPower/UPower.conf
#
### Hardens Default Network Privacy Settings
cp ./modules/syst-settings/network-privacy-hardening.conf /etc/NetworkManager/conf.d/
#
# Sets Plymouth theme:
plymouth-set-default-theme -R joy
#
